name = "Leontopodium"
author = "noahreinalter"
version = "1.3.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7de9c215e78eeab97f257a684c6f55d4fa7dcaf8d193a116fa6b91ecdc032476"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
