name = "Leontopodium"
author = "noahreinalter"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2545f8cbbc6921fe14aa3cf590af3f62956624167fdde0205f2f3c5b3db931b"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
