name = "Leontopodium"
author = "noahreinalter"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a4895d81562e25532154c5b002a4b77196452c4bfb3cd7cad1055924a418739"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
