name = "Leontopodium"
author = "noahreinalter"
version = "1.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af39231f563cbdde6026e857fb670b09853238a1e352861cd8db512901f17553"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
